// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/room/:roomId": {
    params: {
      "roomId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/room/:roomId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/room.tsx": {
    id: "routes/room";
    page: "/room/:roomId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/room": typeof import("./app/routes/room.tsx");
};